

services:
  api:
    image: oussamaht16/firstproject
    ports: 
      - "80:8000"
    #volumes:
    #  - ./:/usr/src/app #يعني زدت volume bind mount يخلي المشروع الموجود على جهازك (الملفات اللي في ./) يتزامن مباشرة مع /usr/src/app داخل الـ container.
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME} 
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # hada howa li rana dyrilo detail ta3o ltht lokn tktb oussama ltht tanik traja3ha oussama o hada ki chghol dns
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME} 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #hadi bch hata lokn nsuprimiw l container wch kan dakhal db myrohch

volumes:
  postgres_data:
