

services:
  api:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./:/usr/src/app #يعني زدت volume bind mount يخلي المشروع الموجود على جهازك (الملفات اللي في ./) يتزامن مباشرة مع /usr/src/app داخل الـ container.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mypassword123
      - DATABASE_HOSTNAME=postgres # hada howa li rana dyrilo detail ta3o ltht lokn tktb oussama ltht tanik traja3ha oussama o hada ki chghol dns
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword123
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #hadi bch hata lokn nsuprimiw l container wch kan dakhal db myrohch

volumes:
  postgres_data:
